/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author joseo
 */
public class TelaFuncPrimeira extends javax.swing.JFrame {

    public String nomeFunc;
    
    public TelaFuncPrimeira(String nomeFunc) {
        this.nomeFunc = nomeFunc;
        initComponents();
        if(this.nomeFunc != null){
            mensagemBemVindo.setText("Bem-vindo, " + this.nomeFunc);
        } else
            mensagemBemVindo.setText("Outras operações");
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoCriarCliente = new javax.swing.JButton();
        botaoCriarVenda1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mensagemBemVindo = new javax.swing.JLabel();
        botaoTelaTrocaPontos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 235, 221));

        botaoCriarCliente.setBackground(new java.awt.Color(92, 184, 92));
        botaoCriarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoCriarCliente.setForeground(new java.awt.Color(245, 235, 221));
        botaoCriarCliente.setText("Criar Cliente");
        botaoCriarCliente.setActionCommand("CriarCliente");
        botaoCriarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarClienteActionPerformed(evt);
            }
        });

        botaoCriarVenda1.setBackground(new java.awt.Color(164, 87, 44));
        botaoCriarVenda1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoCriarVenda1.setForeground(new java.awt.Color(245, 235, 221));
        botaoCriarVenda1.setText("Criar Venda");
        botaoCriarVenda1.setActionCommand("CriarVenda");
        botaoCriarVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarVenda1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(164, 113, 72));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 60));

        jButton4.setBackground(new java.awt.Color(245, 235, 221));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(164, 87, 44));
        jButton4.setText("Voltar");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/minilogo_padaria.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        mensagemBemVindo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        mensagemBemVindo.setForeground(new java.awt.Color(164, 87, 44));
        mensagemBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoTelaTrocaPontos.setBackground(new java.awt.Color(0, 153, 0));
        botaoTelaTrocaPontos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoTelaTrocaPontos.setForeground(new java.awt.Color(245, 235, 221));
        botaoTelaTrocaPontos.setText("Trocar Pontos");
        botaoTelaTrocaPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaTrocaPontosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensagemBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botaoCriarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botaoCriarVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botaoTelaTrocaPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(mensagemBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCriarVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTelaTrocaPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCriarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarClienteActionPerformed
        TelaFuncionarioCadastroCliente telaCadastroClienteFuncionario = new TelaFuncionarioCadastroCliente();
        telaCadastroClienteFuncionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCriarClienteActionPerformed

    private void botaoCriarVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarVenda1ActionPerformed
        TelaFuncAdicionaProdutosALista adicionaProdutosALista = new TelaFuncAdicionaProdutosALista();
        adicionaProdutosALista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCriarVenda1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botaoTelaTrocaPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaTrocaPontosActionPerformed
        TelaTrocaPontos telaTrocaPontos = new TelaTrocaPontos();
        telaTrocaPontos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoTelaTrocaPontosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarCliente;
    private javax.swing.JButton botaoCriarVenda1;
    private javax.swing.JButton botaoTelaTrocaPontos;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensagemBemVindo;
    // End of variables declaration//GEN-END:variables
}
