/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ClienteController;
import controller.ProdutoController;
import controller.VendaController;
import javax.swing.JOptionPane;
import model.bean.Produto;
import model.dao.ClienteDAO;
import model.dao.ProdutoDAO;
import model.dao.impl.VendaDAOImpl;
import service.VendaService;
import model.dao.VendaDAO;
import model.dao.impl.ClienteDAOImpl;
import model.dao.impl.ProdutoDAOImpl;
import service.ClienteService;
import service.ProdutoService;

public class TelaFuncAdicionaProdutosALista extends javax.swing.JFrame {

    private VendaController vendaController;

    ProdutoDAO produtoDao = new ProdutoDAOImpl();
    ProdutoService produtoService = new ProdutoService(produtoDao);
    ProdutoController produtoController = new ProdutoController(produtoService);

    ClienteDAO clienteDAO = new ClienteDAOImpl();
    ClienteService clienteService = new ClienteService(clienteDAO);
    ClienteController clienteController = new ClienteController(clienteService);
    
    public String nomeFunc;

    public TelaFuncAdicionaProdutosALista() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza
        VendaDAO vendaDAO = new VendaDAOImpl();
        VendaService vendaService = new VendaService(vendaDAO);
        this.vendaController = new VendaController(vendaService);
        
    }
    
    public TelaFuncAdicionaProdutosALista(VendaController vendaController) {
        this.vendaController = vendaController; // Atribui a instância passada
        initComponents();
        setLocationRelativeTo(null); // Centraliza
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoIdProduto = new javax.swing.JTextField();
        botaoAdicionar = new javax.swing.JButton();
        botaoProsseguir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoQuantidadeParaVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padaria Rezende's");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 235, 221));

        jPanel2.setBackground(new java.awt.Color(164, 113, 72));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 60));

        jButton4.setBackground(new java.awt.Color(245, 235, 221));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(164, 87, 44));
        jButton4.setText("Voltar");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/minilogo_padaria.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 235, 221));
        jLabel10.setText("Adicionar produto(s) no carrinho");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        campoIdProduto.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        campoIdProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdProdutoActionPerformed(evt);
            }
        });

        botaoAdicionar.setBackground(new java.awt.Color(92, 184, 92));
        botaoAdicionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoAdicionar.setForeground(new java.awt.Color(245, 235, 221));
        botaoAdicionar.setText("Adicionar no carrinho");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoProsseguir.setBackground(new java.awt.Color(164, 113, 72));
        botaoProsseguir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoProsseguir.setForeground(new java.awt.Color(245, 235, 221));
        botaoProsseguir.setText("Ir ao caixa >");
        botaoProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProsseguirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 87, 44));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Insira o ID do produto");

        campoQuantidadeParaVenda.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        campoQuantidadeParaVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoQuantidadeParaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidadeParaVendaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 87, 44));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(campoIdProduto))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoQuantidadeParaVenda)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoIdProduto)
                    .addComponent(campoQuantidadeParaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botaoProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdProdutoActionPerformed

    private void botaoProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProsseguirActionPerformed
        if (vendaController != null && !vendaController.getProdutoList().isEmpty()) { // Adicionei null check para vendaController
        // Corrigido: PASSE A INSTÂNCIA DO VENDAController ATUAL!
        TelaFuncionarioPrincipal telaPrincipalFuncionario = new TelaFuncionarioPrincipal(this.vendaController);
        telaPrincipalFuncionario.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "A lista de produtos no carrinho está vazia. Adicione produtos antes de prosseguir para o caixa!");
           }
    }//GEN-LAST:event_botaoProsseguirActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        try {
            Long armazenaIdProduto = Long.valueOf(campoIdProduto.getText());
            int armazenaQuantidade = Integer.valueOf(campoQuantidadeParaVenda.getText());

            if (armazenaIdProduto == null || armazenaIdProduto <= 0) {
                JOptionPane.showMessageDialog(null, "O ID informado é inválido");
                return;
            }
            
            if(armazenaQuantidade <= 0){
                JOptionPane.showMessageDialog(null, "A quantidade precisa ser maior do que 0");
                return;
            }
            
            Produto produto = produtoDao.findById(armazenaIdProduto);
            
            if(produto.getQuantidade() >= armazenaQuantidade){
                vendaController.addQuantidadeParaVenda(armazenaQuantidade);
                vendaController.addProdutoAoCarrinho(armazenaIdProduto);
                JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso!");
            } else
                JOptionPane.showMessageDialog(null, "Quantidade em estoque é menor do que a preterida para a compra");
        
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um valor válido");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Campo inserido está incorreto!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir produto!");
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaFuncPrimeira telaNovaVenda = new TelaFuncPrimeira(nomeFunc);
        telaNovaVenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void campoQuantidadeParaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeParaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidadeParaVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncAdicionaProdutosALista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncAdicionaProdutosALista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncAdicionaProdutosALista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncAdicionaProdutosALista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaFuncAdicionaProdutosALista().setVisible(true);
                VendaDAO vendaDao = new VendaDAOImpl();
                VendaService vendaService = new VendaService(vendaDao);
                VendaController vendaController = new VendaController(vendaService);
                
                new TelaFuncAdicionaProdutosALista(vendaController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoProsseguir;
    private javax.swing.JTextField campoIdProduto;
    private javax.swing.JTextField campoQuantidadeParaVenda;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
