/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CaixaController;
import controller.GerenteController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Caixa;
import model.bean.Cliente;
import model.bean.Produto;
import model.dao.CaixaDAO;
import model.dao.GerenteDAO;
import model.dao.impl.CaixaDAOImpl;
import model.dao.impl.GerenteDAOImpl;
import service.CaixaService;
import service.GerenteService;

/**
 *
 * @author onata
 */
public class TelaCadastrarFunc extends javax.swing.JFrame {

    GerenteDAO gerenteDAO = new GerenteDAOImpl();
    GerenteService gerenteService = new GerenteService(gerenteDAO);
    GerenteController gerenteController = new GerenteController(gerenteService);
    
    CaixaDAO caixaDAO = new CaixaDAOImpl();
    CaixaService caixaService = new CaixaService(caixaDAO);
    CaixaController caixaController = new CaixaController(caixaService);

    /**
     * Creates new form TelaCadastrarFunc
     */
    public TelaCadastrarFunc() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoCPF = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoNome = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoTelefone = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoCargo = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoSenha = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        campoLogin = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaExibicao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padaria Rezende's Gerente");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(245, 235, 221));
        jPanel1.setForeground(new java.awt.Color(245, 235, 221));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 400));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 87, 44));
        jLabel8.setText("Senha");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 87, 44));
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 87, 44));
        jLabel4.setText("Telefone");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(164, 87, 44));
        jLabel6.setText("Cargo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 87, 44));
        jLabel7.setText("Login");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(164, 87, 44));
        jLabel5.setText("CPF");

        jScrollPane1.setViewportView(campoCPF);

        jScrollPane2.setViewportView(campoNome);

        jScrollPane3.setViewportView(campoTelefone);

        jScrollPane4.setViewportView(campoCargo);

        jScrollPane5.setViewportView(campoSenha);

        jScrollPane6.setViewportView(campoLogin);

        jButton1.setBackground(new java.awt.Color(92, 184, 92));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(245, 235, 221));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(164, 113, 72));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 60));

        jButton5.setBackground(new java.awt.Color(245, 235, 221));
        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(164, 87, 44));
        jButton5.setText("Voltar");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/minilogo_padaria.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 235, 221));
        jLabel10.setText("Gerenciamento de funcionário");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jButton5)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoAtualizar.setBackground(new java.awt.Color(51, 102, 255));
        botaoAtualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(245, 235, 221));
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoDeletar.setBackground(new java.awt.Color(217, 83, 79));
        botaoDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(245, 235, 221));
        botaoDeletar.setText("Deletar");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        tabelaExibicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone", "Cargo", "Login", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaExibicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaExibicaoMouseClicked(evt);
            }
        });
        tabelaExibicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaExibicaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaExibicaoKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tabelaExibicao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(jLabel7)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8)
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TelaPrincipalGerente telaPrincipalGerente = new TelaPrincipalGerente();
        telaPrincipalGerente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = campoNome.getText();
        String CPF = campoCPF.getText();
        String telefone = campoTelefone.getText();
        String cargo = campoCargo.getText();
        String login = campoLogin.getText();
        String senha = campoSenha.getText();

        try {
            gerenteController.createCaixa(nome, CPF, telefone, cargo, login, senha);
            campoNome.setText("");
            campoCPF.setText("");
            campoTelefone.setText("");
            campoCargo.setText("");
            campoLogin.setText("");
            campoSenha.setText("");
            readTable();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Campos inválidos!");
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o caixa!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed

        int selectedRow = tabelaExibicao.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para atualizar");
            return;
        }
        try {

            Long idFuncionario = (Long) tabelaExibicao.getValueAt(selectedRow, 0);

            String novoNome = campoNome.getText();
            String novoCPF = campoCPF.getText();
            String novoTelefone = campoTelefone.getText();
            String novoCargo = campoCargo.getText();
            String novoLogin = campoLogin.getText();
            String novaSenha = campoSenha.getText();

            Caixa caixa = new Caixa(novoNome, novoCPF, novoTelefone, novoCargo, novoLogin, novaSenha);

            gerenteController.updateCaixa(idFuncionario, novoNome, novoCPF, novoTelefone, novoCargo, novoLogin, novaSenha);
            readTable();
            
            campoNome.setText("");
            campoCPF.setText("");
            campoTelefone.setText("");
            campoCargo.setText("");
            campoLogin.setText("");
            campoSenha.setText("");
                
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro de formato nos dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar caixa: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        int selectedRow = tabelaExibicao.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um caixa para deletar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja deletar este caixa?",
                "Confirmar Deleção",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Obtenha o ID do produto da tabela (primeira coluna)
                Long idCaixa = (Long) tabelaExibicao.getValueAt(selectedRow, 0);

                gerenteController.deleteCaixa(idCaixa);

                JOptionPane.showMessageDialog(this, "Caixa deletado com sucesso!");
                readTable();
                
                campoNome.setText("");
                campoCPF.setText("");
                campoTelefone.setText("");
                campoCargo.setText("");
                campoLogin.setText("");
                campoSenha.setText("");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao deletar caixa: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_botaoDeletarActionPerformed

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaExibicao.getModel();
        modelo.setNumRows(0);

        try {
            List<Caixa> caixas = caixaController.readCaixa();
            if (caixas != null) { // Importante verificar se não é nulo
                for (Caixa c : caixas) {
                    modelo.addRow(new Object[]{
                        c.getId(),
                        c.getNome(),
                        c.getCPF(),
                        c.getTelefone(),
                        c.getCargo(),
                        c.getLogin(),
                        c.getSenha()
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível carregar os produtos.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace(); // Imprime o stack trace para depuração
             JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tabelaExibicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaExibicaoKeyPressed
        if (tabelaExibicao.getSelectedRow() != -1) {
            
            campoNome.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 1).toString());
            campoCPF.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 2).toString());
            campoTelefone.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 3).toString());
            campoCargo.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 4).toString());
            campoLogin.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 5).toString());
            campoSenha.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 6).toString());
            
            int linhaSelecionada = tabelaExibicao.getSelectedRow();
        }
    }//GEN-LAST:event_tabelaExibicaoKeyPressed

    private void tabelaExibicaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaExibicaoKeyReleased
        if (tabelaExibicao.getSelectedRow() != -1) {
            
            campoNome.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 1).toString());
            campoCPF.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 2).toString());
            campoTelefone.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 3).toString());
            campoCargo.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 4).toString());
            campoLogin.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 5).toString());
            campoSenha.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 6).toString());
            
            int linhaSelecionada = tabelaExibicao.getSelectedRow();
        }
    }//GEN-LAST:event_tabelaExibicaoKeyReleased

    private void tabelaExibicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaExibicaoMouseClicked
        if (tabelaExibicao.getSelectedRow() != -1) {
            
            campoNome.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 1).toString());
            campoCPF.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 2).toString());
            campoTelefone.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 3).toString());
            campoCargo.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 4).toString());
            campoLogin.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 5).toString());
            campoSenha.setText(tabelaExibicao.getValueAt(tabelaExibicao.getSelectedRow(), 6).toString());
            
            int linhaSelecionada = tabelaExibicao.getSelectedRow();
        }
    }//GEN-LAST:event_tabelaExibicaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JTextPane campoCPF;
    private javax.swing.JTextPane campoCargo;
    private javax.swing.JTextPane campoLogin;
    private javax.swing.JTextPane campoNome;
    private javax.swing.JTextPane campoSenha;
    private javax.swing.JTextPane campoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tabelaExibicao;
    // End of variables declaration//GEN-END:variables
}
